### ISSUE TITLE
Add README to Project

### ISSUE THREAD

**Issue by chankruze** [chankruze/snipbin#1]
Add a README:

1. Describing the whole installation process.
2. How to run and start the project
3. And any other useful info

**Comment by k40t1k-sys** [comment]
@chankruze please assign me this issue.

**Comment by chankruze** [comment]
@k40t1k-sys Next time if you want to close an issue with a PR, write a commit message like this `Fixes #{Issue Number} |  <Your Message>`. Now as soon as your PR is merged, the respective Issue will be marked as closed with the commit hash.

The issue will be closed like this:
![image](https://user-images.githubusercontent.com/29806845/135984860-22f71ee3-9479-4239-9360-36757d11f83e.png)

![image](https://user-images.githubusercontent.com/29806845/135984939-60e8098d-5e55-4ef8-b85c-a4407616343f.png)
